### ISSUE TITLE
pydantic versioning in setup.py introduces a breaking change

### ISSUE THREAD

**Issue by sjangranfer** [glichtner/fhir.resources#1]
reference: https://github.com/pydantic/pydantic#pydantic-v110-vs-v2
https://github.com/glichtner/fhir.resources/blob/da51d156181dfd1c53e9df21566fbfdad110b8db/setup.py#L11

setup.py should either restrict pydantic version to below 2.0
or there needs to be code changes compatible with pydantic>=2.0

error traceback encountered
```
  File "/home/sandeep/master/lib64/python3.8/site-packages/nferx_py/files/handler.py", line 9, in <module>
    from fhir.resources import construct_fhir_element
  File "/home/sandeep/master/lib64/python3.8/site-packages/fhir/resources/__init__.py", line 5, in <module>
    from fhir.resources.core.fhirabstractmodel import FHIRAbstractModel
  File "/home/sandeep/master/lib64/python3.8/site-packages/fhir/resources/core/fhirabstractmodel.py", line 13, in <module>
    from pydantic.class_validators import ROOT_VALIDATOR_CONFIG_KEY, root_validator
ImportError: cannot import name 'ROOT_VALIDATOR_CONFIG_KEY' from 'pydantic.class_validators' 
```

**Comment by glichtner** [comment]
Hi @sjangranfer ,

Thank you for reporting. I have changed the requirement to pydantic <2.0. Please let me know if you encounter additional issues (and feel free to re-open the issues if you do).
