### ISSUE TITLE
MedicationAdministration Dosage issue

### ISSUE THREAD

**Issue by acabrelles** [glichtner/fhir.resources#2]
This is my first time submitting an issue in general, so please pardon if my etiquette is a bit lacking, I may need a bit of guidance.
First of all, thank you for the creation of this library, it has been honestly a lifesaver in many regards.

After quite the efforts in troubleshooting, I have reached a roadblock. It may be a basic mistake I'm making, but I don't know how to solve it, and I don't know if it may be a bug (I assume it's more of an oversight on my part, if anything).

I have been in charge of making some script that automatically translates a structured CSV into a FHIR json format, and to make things automatic, I have been creating some functions that use the resources of your library. For context, I am still working on 4.3, instead of 5.0 as some requirements have changed and it would throw the process off by quite the margin.

Now, the ACTUAL issue happens when I attempt to make a function that automates the creation of MedicationAdministration resources. Every time I add a `rateRatio` to the `dosage`, it overwrites `dose`.

Basically, simplified, it's something like
`def medadm([...], medication_dose, medication_units, medication_units_dictionary, accumulated_dose, accumulated_units)`
with `medication_units`and `medication_units_dictionary` I get a structured dictionary where the only missing field is the value. And so, I do
` dosage_dict = medication_units_dict[medication_units]
   dosage_dict["value"] = medication_dose
   medication_resource["dosage"] = {"dose":dosage_dict}`
So far, so good. if nothing else happened, this would work just fine. But then, I also get an accumulated dose that is in a fraction, as it's basically a `rateRatio`, and so, I do, for the numerator:
`acc_dosage_dict = medication_units_dict[accumulated_units]
  acc_dosage_dict["value"] = accumulated_dose`
For the denominator I already placed a preestablished one manually. Let's call it `denom`. I used `medication_units_dict` again since it's the same dictionary for both.
To confirm my dictionaries are correct, I also printed both `dosage_dict` and `acc_dosage_dict`, and both are good and different.
As `dosage` has already been created, I only need to add another key to it.
`medication_resource["dosage"]["rateRatio"]= {"numerator":acc_dosage_dict,"denominator":denom}`

And now, with the resulting resource, after parsed... I get returned a `MedicationAdministration` where both the `dose` and the `numerator` of `rateRatio` have the value of the latter.

The code is a bit more complex, but both `dose` and `rateRatio` never interact with each other in my code, other than, obviously, `dosage` itself. I haven't found them to interact otherwise, at least. The problem persists even if I force the key to be overwritten again with `medication_resource["dosage"]["dose"] = dosage_dict` after the `rateRatio` line.

Thank you for your attention

**Comment by acabrelles** [comment]
Okay, pardon me. I haven't found the mistake, but after much further testing I've found out it is not a problem with the resource itself. I will keep working on finding the problem out, it has to be something else I am doing!

**Comment by glichtner** [comment]
Hi @acabrelles,

sorry for not responding earlier.

Please be advised that this repository is a fork from https://github.com/nazrulworld/fhir.resources, which is the original repository. I had forked and recreated the repository, because I needed R5 resources during its development, which was not available from nazrulworlds's repository. However, I see that in the meantime they also implemented it. In any case, I recommend using their repository for R4, as they may have addressed some issues that may have been in the code at the time when I forked it and thus still in this repository here, but not anymore in theirs.

Hope that helps.
